# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 1
  start_block: 0
  contracts:
  - name: PudgyPenguins
    address:
    - 0xBd3531dA5CF5857e7CfAA92426877b022e612cf8
    handler: src/EventHandlers.ts
    events:
    - event: CreatePenguin(uint256 indexed id)
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
unordered_multichain_mode: true
preload_handlers: true
